### ISSUE TITLE
How to push parameter to custom user command

### ISSUE THREAD

**Issue by virutmath** [kenjis/codeigniter-cli#9]
I want to create some custom command for auto procedure and I use custom user command like you demo. But I want to use some parameter in this. How can I do?

**Comment by kenjis** [comment]
See https://github.com/kenjis/codeigniter-cli/blob/master/src/Command/Run.php#L17
This is the source for `run` command:
~~~
USAGE
    run <controller>
    run <controller> <method>
    run <controller> <method> <arg1>
    run <controller> <method> <arg1> <arg2> [...]
~~~
